apiVersion: v1
kind: Service
metadata:
  name: express-app-service
  labels:
    app: express-app
spec:
  selector:
    app: express-app
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  - name: metrics
    port: 3000
    targetPort: 3000
  type: ClusterIP